//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFHostForWF1Test.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IStateMachineService")]
    public interface IStateMachineService {
        
        // CODEGEN: Generating message contract since the operation CreateFlow is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStateMachineService/CreateFlow", ReplyAction="http://tempuri.org/IStateMachineService/CreateFlowResponse")]
        WCFHostForWF1Test.ServiceReference1.CreateFlowResponse CreateFlow(WCFHostForWF1Test.ServiceReference1.CreateFlowRequest request);
        
        // CODEGEN: Generating message contract since the operation ChangeAction is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStateMachineService/ChangeAction", ReplyAction="http://tempuri.org/IStateMachineService/ChangeActionResponse")]
        WCFHostForWF1Test.ServiceReference1.ChangeActionResponse ChangeAction(WCFHostForWF1Test.ServiceReference1.ChangeActionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStateMachineService/GetAction", ReplyAction="http://tempuri.org/IStateMachineService/GetActionResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Action")]
        string GetAction(System.Guid Id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateFlowRequest {
        
        public CreateFlowRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateFlowResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CreateFlowResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Guid FlowId;
        
        public CreateFlowResponse() {
        }
        
        public CreateFlowResponse(System.Guid FlowId) {
            this.FlowId = FlowId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ChangeAction", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ChangeActionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Guid Id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Action;
        
        public ChangeActionRequest() {
        }
        
        public ChangeActionRequest(System.Guid Id, string Action) {
            this.Id = Id;
            this.Action = Action;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangeActionResponse {
        
        public ChangeActionResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStateMachineServiceChannel : WCFHostForWF1Test.ServiceReference1.IStateMachineService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StateMachineServiceClient : System.ServiceModel.ClientBase<WCFHostForWF1Test.ServiceReference1.IStateMachineService>, WCFHostForWF1Test.ServiceReference1.IStateMachineService {
        
        public StateMachineServiceClient() {
        }
        
        public StateMachineServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StateMachineServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StateMachineServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StateMachineServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCFHostForWF1Test.ServiceReference1.CreateFlowResponse WCFHostForWF1Test.ServiceReference1.IStateMachineService.CreateFlow(WCFHostForWF1Test.ServiceReference1.CreateFlowRequest request) {
            return base.Channel.CreateFlow(request);
        }
        
        public System.Guid CreateFlow() {
            WCFHostForWF1Test.ServiceReference1.CreateFlowRequest inValue = new WCFHostForWF1Test.ServiceReference1.CreateFlowRequest();
            WCFHostForWF1Test.ServiceReference1.CreateFlowResponse retVal = ((WCFHostForWF1Test.ServiceReference1.IStateMachineService)(this)).CreateFlow(inValue);
            return retVal.FlowId;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCFHostForWF1Test.ServiceReference1.ChangeActionResponse WCFHostForWF1Test.ServiceReference1.IStateMachineService.ChangeAction(WCFHostForWF1Test.ServiceReference1.ChangeActionRequest request) {
            return base.Channel.ChangeAction(request);
        }
        
        public void ChangeAction(System.Guid Id, string Action) {
            WCFHostForWF1Test.ServiceReference1.ChangeActionRequest inValue = new WCFHostForWF1Test.ServiceReference1.ChangeActionRequest();
            inValue.Id = Id;
            inValue.Action = Action;
            WCFHostForWF1Test.ServiceReference1.ChangeActionResponse retVal = ((WCFHostForWF1Test.ServiceReference1.IStateMachineService)(this)).ChangeAction(inValue);
        }
        
        public string GetAction(System.Guid Id) {
            return base.Channel.GetAction(Id);
        }
    }
}
